ztty_column_filter  line type zstr_dictionary
ztty_dictionary     line type zstr_dictionary
ztty_eezz_json      line type zstr_eezz_json
ZTTY_EEZZ_PARAMETER line type ZSTR_EEZZ_JSON
ZTTY_EEZZ_ROW       line type ZSTR_CELL
ZTTY_GLOBAL_SYMBOLS line type ZTTY_GLOBAL_SYMBOLS
ZTTY_MESSAGES       line type ZSTR_MESSAGE
ZTTY_RANGE          line type integer
ZTTY_SFLIGHT        line type zstr_sflight
ZTTY_SORT           line type zstr_sort
ZTTY_UPDATE         line type zstr_update